### ISSUE TITLE
您好，请求一下：数据集、图片处理格式、您的预训练模型

### ISSUE THREAD

**Issue by Faunder-fld** [haifangong/TRFE-Net-for-thyroid-nodule-segmentation#1]
大佬你好，我最近在做腮腺的医学图像分割，考虑做迁移学习。
- TN3K 的数据集方便发个网盘吗？或者发个链接；
- 如果数据集不能共享，希望您能告知图片处理的格式；
- 以及可以把您的预训练模型放出来吗？我想做迁移学习的对比试验；

**Comment by haifangong** [comment]
您好，感谢您对我们工作的关注。预训练模型和结节分割数据已经公开在readme文档，如果本工作对你有帮助的话欢迎引用

**Comment by Faunder-fld** [comment]
好的，十分感谢！！

**Comment by ghost** [comment]
The data-set link is not working, How can i download that?
