### ISSUE TITLE
Excuse me, I only have the slice of thyroid CT and the mask of the corresponding thyroid nodule. Can I use this item?

### ISSUE THREAD

**Issue by BelieferQAQ** [haifangong/TRFE-Net-for-thyroid-nodule-segmentation#4]
Excuse me, I only have the slice of thyroid CT and the mask of the corresponding thyroid nodule. Can I use this item?

**Comment by haifangong** [comment]
Sorry for the late reply. You may try to use this project if the CT imaging is 2-d.
